version: "3.1"
services:

  postgresdb:
    container_name: jirapostgresql
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: jira_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweasdzxc

    # Zookeeper: localhost:22181
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

    # Kafka. Bootsrap: localhost:29092
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    # UI for Apache Kafka (https://github.com/provectus/kafka-ui): http://localhost:8090/
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      # volumes:
      #   - ./kafka-ui/dynamic_config.yml:/etc/kafkaui/dynamic_config.yaml
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
    restart: unless-stopped
#  kafka:
#    image: wurstmeister/kafka:2.13-2.6.0
#    container_name: kafka
#    hostname: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#      - "9101:9101"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTER:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_LISTENERS: INTERNAL://kafka:29092,OUTER://localhost:9092
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,OUTER://localhost:9092
#      KAFKA_JMX_PORT: 9101
#      KAFKA_JMX_HOSTNAME: localhost
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
#      KAFKA_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_LOG_DIRS: /kafka/kafka-logs


#  employee-service:
#    container_name: employee-service
#    image: employee-service
#    build:
#      context: ../EmployeeService
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresdb
#      - kafka
#    restart: on-failure
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://petpostgres:5432/petdoctordb
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 1qaz2wsx
#      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
#
#  enrollment-service:
#    container_name: enrollment-service
#    image: enrollment-service
#    build:
#      context: ../EnrollmentService
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgresdb
#      - kafka
#    restart: on-failure
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://petpostgres:5432/petdoctordb
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 1qaz2wsx
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
