spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jira_db
    username: postgres
    password: qweasdzxc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: PostgreSql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    url: jdbc:postgresql://localhost:5433/jira_db
    user: postgres
    password: qweasdzxc
    enabled: true
    change-log: classpath:db/changelog/Changelog.xml
  kafka:
    enabled: false
    bootstrap-servers: localhost:29092
    consumer:
      group-id: local-jira
      auto-offset-reset: earliest
  redis:
    host: localhost
    port: 6379
feign:
  client.config.default:
    readTimeout: 5000
    connectTimeout: 5000
    loggerLevel: FULL
jira:
  external:
    kafkaProduceTask: http://localhost:8089
