spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jira_db
    username: postgres
    password: qweasdzxc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: PostgreSql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true